# Generated by Django 4.2.5 on 2023-09-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cart_user_is_active_user_is_staff_cartitem_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
